---
title: "BirdFlow model summary for `r bf$species$common_name`"
subtitle: "`r sub('\\.hdf5$', '', ll_df$model[1])`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Hyperparameters

```{r hyperparameters, echo = FALSE}
kableExtra::kbl(
  ll_df[1, c('de_ratio', 'obs_prop', 'dist_pow', 'dist_weight', 'ent_weight', 'obs_weight')]
  )
```

Model evalutaion season: `r params$season`

```{r spacer1, echo = FALSE}
```

Correlation and calibration

```{r cor_cal, echo = FALSE}
kableExtra::kbl(
  ll_df[1, c('end_traverse_cor', 'pit_row', 'pit_col', 'pit_in_95')]
  )
```

Desirability

```{r desirability, echo = FALSE}
kableExtra::kbl(
  ll_df[1, c('d_pit_row', 'd_pit_col', 'd_pit_in_95', 'pit_d', 'etc_d', 'str_d', 'nso_d', 'overall_des')]
  )
```

Simulated route characteristics

```{r route_char, echo = FALSE, message = FALSE}
quick_visualize_routes(1, 10, params$season, dir = params$hdf_dir)
kableExtra::kbl(
  ll_df[1, c('straightness', 'length', 'displacement', 'n_stopovers')]
  )
```

