name: pkgdown

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Pandoc is used by pkgdown when rendering pages
      - uses: r-lib/actions/setup-pandoc@v2

      # Set up R
      - uses: r-lib/actions/setup-r@v2

      # Install dependencies needed to build the website
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, any::remotes, local::.
          needs: website

      # IMPORTANT: Install package without vignettes to avoid knitting on CI
      - name: Install package (no vignettes)
        run: Rscript -e 'remotes::install_local(".", build_vignettes = FALSE, upgrade = "never")'

      # Build the pkgdown site. We rely on prebuilt inst/doc/ for Articles.
      - name: Build site
        run: Rscript -e 'pkgdown::build_site(new_process = FALSE, install = FALSE)'

      # Publish docs/ to GitHub Pages
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        
